"use client";

import { useEffect, useMemo, useState } from "react";
import type { AuthResponse, CheckoutResponse, JobSummary, Locale, PaymentMethodSummary, ServiceCategory, SessionUser } from "@fixmy/contracts";
import { ArrowLeft, Bell, Check, ChevronRight, Clock3, Home, LogOut, Menu, MessageCircle, Monitor, MoreHorizontal, Phone, Plus, Search, Sparkles, Star, Truck, UserRound, Wrench, X } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/backend";
const locales: Locale[] = ["es", "fr", "nl", "en", "pt"];
const localeNames: Record<Locale, string> = { es: "ES", fr: "FR", nl: "NL", en: "EN", pt: "PT" };

const translations = {
  es: { tagline1:"Lo arreglamos.",tagline2:"Tú lo disfrutas.",taglineSub:"Tus problemas cotidianos, resueltos con un toque.",getStarted:"Comenzar",login:"Entrar",register:"Crear cuenta",welcome:"Bienvenido a FIX MY",hello:"Hola",need:"¿Con qué necesitas",help:"ayuda",today:"hoy?",search:"Buscar un servicio...",home:"Hogar",repairs:"Reparaciones",tech:"Tecnología",moving:"Mudanzas",cleaning:"Limpieza",more:"Más",fast:"¿Necesitas ayuda rápido?",fastSub:"Conecta con un profesional verificado en minutos.",requestNow:"Solicitar ahora",recent:"Solicitudes recientes",viewAll:"Ver todas",noRequests:"Aún no hay solicitudes",requests:"Solicitudes",messages:"Mensajes",profile:"Perfil",myRequest:"Mi solicitud",inProgress:"En curso",onWay:"¡Tu Pro está en camino!",arrival:"Llegada estimada",minutes:"min",plumber:"Fontanero",rateTitle:"Valorar y opinar",experience:"¿Cómo fue tu experiencia?",great:"¡Genial!",comment:"Deja un comentario (opcional)...",submit:"Enviar valoración",skip:"Omitir",email:"Correo electrónico",password:"Contraseña",name:"Nombre completo",continue:"Continuar",logout:"Cerrar sesión",service:"Servicio",title:"Título",description:"Descripción",address:"Dirección",budget:"Presupuesto (€)",review:"Revisar solicitud",pay:"Pagar y publicar",back:"Atrás",success:"Solicitud publicada",successSub:"El pago de prueba se confirmó y los Pros ya pueden verla.",close:"Cerrar",required:"Completa todos los campos y usa un presupuesto mínimo de €10.",apiError:"No se pudo completar la operación.",changePassword:"Crea una nueva contraseña",temporary:"Contraseña temporal",newPassword:"Nueva contraseña",save:"Guardar y continuar",ratingSaved:"Gracias por tu valoración.",demoHint:"También puedes usar la cuenta demo indicada en la guía."},
  fr: { tagline1:"Nous réparons.",tagline2:"Vous profitez.",taglineSub:"Vos problèmes quotidiens, résolus en un geste.",getStarted:"Commencer",login:"Connexion",register:"Créer un compte",welcome:"Bienvenue sur FIX MY",hello:"Bonjour",need:"De quoi avez-vous besoin",help:"d'aide",today:"aujourd'hui ?",search:"Rechercher un service...",home:"Maison",repairs:"Réparations",tech:"Tech",moving:"Déménagement",cleaning:"Nettoyage",more:"Plus",fast:"Besoin d'aide rapidement ?",fastSub:"Trouvez un professionnel vérifié en quelques minutes.",requestNow:"Demander",recent:"Demandes récentes",viewAll:"Voir tout",noRequests:"Aucune demande pour le moment",requests:"Demandes",messages:"Messages",profile:"Profil",myRequest:"Ma demande",inProgress:"En cours",onWay:"Votre Pro est en route !",arrival:"Arrivée estimée",minutes:"min",plumber:"Plombier",rateTitle:"Noter et commenter",experience:"Comment s'est passée votre expérience ?",great:"Super !",comment:"Laisser un commentaire (facultatif)...",submit:"Envoyer l'avis",skip:"Passer",email:"E-mail",password:"Mot de passe",name:"Nom complet",continue:"Continuer",logout:"Déconnexion",service:"Service",title:"Titre",description:"Description",address:"Adresse",budget:"Budget (€)",review:"Vérifier la demande",pay:"Payer et publier",back:"Retour",success:"Demande publiée",successSub:"Le paiement test est confirmé et les Pros peuvent la voir.",close:"Fermer",required:"Complétez tous les champs avec un budget minimum de 10 €.",apiError:"Impossible de terminer l'opération.",changePassword:"Créez un nouveau mot de passe",temporary:"Mot de passe temporaire",newPassword:"Nouveau mot de passe",save:"Enregistrer et continuer",ratingSaved:"Merci pour votre avis.",demoHint:"Vous pouvez aussi utiliser le compte démo du guide."},
  nl: { tagline1:"Wij maken het.",tagline2:"Jij geniet ervan.",taglineSub:"Dagelijkse problemen opgelost met één tik.",getStarted:"Aan de slag",login:"Inloggen",register:"Account maken",welcome:"Welkom bij FIX MY",hello:"Hallo",need:"Waarmee heb je vandaag",help:"hulp",today:"nodig?",search:"Zoek een dienst...",home:"Woning",repairs:"Reparaties",tech:"Tech",moving:"Verhuizen",cleaning:"Schoonmaak",more:"Meer",fast:"Snel hulp nodig?",fastSub:"Vind binnen enkele minuten een geverifieerde Pro.",requestNow:"Nu aanvragen",recent:"Recente aanvragen",viewAll:"Alles bekijken",noRequests:"Nog geen aanvragen",requests:"Aanvragen",messages:"Berichten",profile:"Profiel",myRequest:"Mijn aanvraag",inProgress:"Bezig",onWay:"Je Pro is onderweg!",arrival:"Geschatte aankomst",minutes:"min",plumber:"Loodgieter",rateTitle:"Beoordelen",experience:"Hoe was je ervaring?",great:"Geweldig!",comment:"Laat een reactie achter (optioneel)...",submit:"Beoordeling sturen",skip:"Overslaan",email:"E-mail",password:"Wachtwoord",name:"Volledige naam",continue:"Doorgaan",logout:"Uitloggen",service:"Dienst",title:"Titel",description:"Beschrijving",address:"Adres",budget:"Budget (€)",review:"Aanvraag nakijken",pay:"Betalen en publiceren",back:"Terug",success:"Aanvraag gepubliceerd",successSub:"De testbetaling is bevestigd en Pros kunnen ze nu zien.",close:"Sluiten",required:"Vul alle velden in en gebruik minimaal €10 budget.",apiError:"De bewerking kon niet worden voltooid.",changePassword:"Maak een nieuw wachtwoord",temporary:"Tijdelijk wachtwoord",newPassword:"Nieuw wachtwoord",save:"Opslaan en doorgaan",ratingSaved:"Bedankt voor je beoordeling.",demoHint:"Je kunt ook het demo-account uit de handleiding gebruiken."},
  en: { tagline1:"We fix it.",tagline2:"You enjoy it.",taglineSub:"Your everyday problems, solved in a tap.",getStarted:"Get Started",login:"Log In",register:"Create account",welcome:"Welcome to FIX MY",hello:"Hello",need:"What do you need",help:"help",today:"with today?",search:"Search for a service...",home:"Home",repairs:"Repairs",tech:"Tech",moving:"Moving",cleaning:"Cleaning",more:"More",fast:"Need help fast?",fastSub:"Get matched with a verified pro in minutes.",requestNow:"Request Now",recent:"Recent Requests",viewAll:"View all",noRequests:"No requests yet",requests:"Requests",messages:"Messages",profile:"Profile",myRequest:"My Request",inProgress:"In Progress",onWay:"Your pro is on the way!",arrival:"Estimated arrival",minutes:"min",plumber:"Plumber",rateTitle:"Rate & Review",experience:"How was your experience?",great:"Great!",comment:"Leave a comment (optional)...",submit:"Submit Review",skip:"Skip",email:"Email",password:"Password",name:"Full name",continue:"Continue",logout:"Log out",service:"Service",title:"Title",description:"Description",address:"Address",budget:"Budget (€)",review:"Review request",pay:"Pay and publish",back:"Back",success:"Request published",successSub:"The test payment is confirmed and Pros can now see it.",close:"Close",required:"Complete every field and use a minimum €10 budget.",apiError:"The operation could not be completed.",changePassword:"Create a new password",temporary:"Temporary password",newPassword:"New password",save:"Save and continue",ratingSaved:"Thank you for your review.",demoHint:"You can also use the demo account listed in the guide."},
  pt: { tagline1:"Nós consertamos.",tagline2:"Você aproveita.",taglineSub:"Seus problemas do dia a dia resolvidos em um toque.",getStarted:"Começar",login:"Entrar",register:"Criar conta",welcome:"Bem-vindo ao FIX MY",hello:"Olá",need:"Com o que você precisa de",help:"ajuda",today:"hoje?",search:"Buscar um serviço...",home:"Casa",repairs:"Reparos",tech:"Tecnologia",moving:"Mudanças",cleaning:"Limpeza",more:"Mais",fast:"Precisa de ajuda rápida?",fastSub:"Encontre um profissional verificado em minutos.",requestNow:"Solicitar agora",recent:"Pedidos recentes",viewAll:"Ver todos",noRequests:"Ainda não há pedidos",requests:"Pedidos",messages:"Mensagens",profile:"Perfil",myRequest:"Meu pedido",inProgress:"Em andamento",onWay:"Seu Pro está a caminho!",arrival:"Chegada estimada",minutes:"min",plumber:"Encanador",rateTitle:"Avaliar",experience:"Como foi sua experiência?",great:"Ótimo!",comment:"Deixe um comentário (opcional)...",submit:"Enviar avaliação",skip:"Pular",email:"E-mail",password:"Senha",name:"Nome completo",continue:"Continuar",logout:"Sair",service:"Serviço",title:"Título",description:"Descrição",address:"Endereço",budget:"Orçamento (€)",review:"Revisar pedido",pay:"Pagar e publicar",back:"Voltar",success:"Pedido publicado",successSub:"O pagamento de teste foi confirmado e os Pros já podem vê-lo.",close:"Fechar",required:"Preencha todos os campos e use um orçamento mínimo de €10.",apiError:"Não foi possível concluir a operação.",changePassword:"Crie uma nova senha",temporary:"Senha temporária",newPassword:"Nova senha",save:"Salvar e continuar",ratingSaved:"Obrigado pela sua avaliação.",demoHint:"Você também pode usar a conta demo indicada no guia."}
} as const;
type ClientCopy = { [K in keyof typeof translations.es]: string };

type Screen = "splash" | "home" | "request" | "review";
type Draft = { categoryId: string; title: string; description: string; address: string; budget: string; lat: number; lng: number };
const emptyDraft: Draft = { categoryId:"", title:"", description:"", address:"Brussels 1000, Belgium", budget:"85", lat:50.8467, lng:4.3525 };

function BubbleLogo(){return <div className="bubble-logo" aria-label="FIX MY"><div><b>F</b><b>I</b><b>X</b></div><div><b>M</b><b>Y</b><small>.HELP</small></div><i/></div>}
function ToolCloud(){return <div className="tool-cloud" aria-hidden="true"><i/><i/><i/><Wrench/><Wrench/><span>●</span><b>✦</b></div>}
function BubbleIllustration({kind}:{kind:"person"|"clock"|"faucet"|"van"|"thumb"}){return <div className={`bubble-art ${kind}`} aria-hidden="true"><div className="art-main">{kind==="person"?<><i/><b/><span/></>:kind==="clock"?<><Clock3/><i/><b/></>:kind==="faucet"?<><span/><i/><b/></>:kind==="van"?<><Truck/><i/><b/></>:<><span>★</span><b>👍</b><i>✦</i></>}</div></div>}
function categoryIcon(slug:string){if(slug.includes("tech"))return <Monitor/>;if(slug.includes("moving"))return <Truck/>;if(slug.includes("clean"))return <Sparkles/>;if(slug.includes("home"))return <Home/>;return <Wrench/>}

export default function HomePage(){
  const [locale,setLocale]=useState<Locale>("es");
  const [screen,setScreen]=useState<Screen>("splash");
  const [token,setToken]=useState("");
  const [user,setUser]=useState<SessionUser|null>(null);
  const [categories,setCategories]=useState<ServiceCategory[]>([]);
  const [jobs,setJobs]=useState<JobSummary[]>([]);
  const [job,setJob]=useState<JobSummary|null>(null);
  const [authOpen,setAuthOpen]=useState(false);
  const [authMode,setAuthMode]=useState<"login"|"register">("login");
  const [requestOpen,setRequestOpen]=useState(false);
  const [requestStep,setRequestStep]=useState(1);
  const [draft,setDraft]=useState<Draft>(emptyDraft);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [rating,setRating]=useState(4);
  const t=translations[locale] as ClientCopy;
  const selectedCategory=useMemo(()=>categories.find(c=>c.id===draft.categoryId),[categories,draft.categoryId]);

  useEffect(()=>{
    const savedLocale=(localStorage.getItem("fixmy_locale") as Locale|null)??"es";
    if(locales.includes(savedLocale))setLocale(savedLocale);
    const savedToken=localStorage.getItem("fixmy_client_token")??"";
    setToken(savedToken);
    fetch(`${API}/api/categories`).then(r=>r.ok?r.json():Promise.reject()).then((items:ServiceCategory[])=>{setCategories(items);if(items[0])setDraft(d=>({...d,categoryId:d.categoryId||items[0]!.id}))}).catch(()=>setError(t.apiError));
    if(savedToken)setScreen("home");
  },[]);
  useEffect(()=>{localStorage.setItem("fixmy_locale",locale);document.documentElement.lang=locale},[locale]);
  useEffect(()=>{if(token)void refresh()},[token]);

  async function api(path:string,options:RequestInit={}){const response=await fetch(`${API}/api${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...options.headers}});const body=await response.json().catch(()=>({}));if(response.status===401){logout();throw new Error(t.login)}if(!response.ok)throw new Error(Array.isArray(body.message)?body.message.join(". "):body.message??t.apiError);return body}
  async function refresh(){try{const me:SessionUser=await api("/auth/me");if(me.role!=="CLIENT")throw new Error(t.apiError);setUser(me);if(!me.mustChangePassword){const list:JobSummary[]=await api("/jobs/mine");setJobs(list);if(job){const current=list.find(item=>item.id===job.id);if(current)setJob(current)}}}catch(caught){setError(caught instanceof Error?caught.message:t.apiError)}}
  async function submitAuth(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);try{const path=authMode==="login"?"/auth/login":"/auth/register/client";const response=await fetch(`${API}/api${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),password:form.get("password")})});const body=await response.json();if(!response.ok)throw new Error(body.message??t.apiError);const auth=body as AuthResponse;if(auth.user.role!=="CLIENT")throw new Error(t.apiError);localStorage.setItem("fixmy_client_token",auth.token);setToken(auth.token);setUser(auth.user);setAuthOpen(false);setScreen("home")}catch(caught){setError(caught instanceof Error?caught.message:t.apiError)}finally{setLoading(false)}}
  async function changeRequiredPassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const form=new FormData(event.currentTarget);try{await api("/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword:form.get("currentPassword"),newPassword:form.get("newPassword")})});setUser(current=>current?{...current,mustChangePassword:false}:current);await refresh()}catch(caught){setError(caught instanceof Error?caught.message:t.apiError)}finally{setLoading(false)}}
  function logout(){localStorage.removeItem("fixmy_client_token");setToken("");setUser(null);setJobs([]);setJob(null);setScreen("splash")}
  function startRequest(categoryId?:string){if(!user){setAuthMode("register");setAuthOpen(true);return}setDraft(d=>({...d,categoryId:categoryId||d.categoryId}));setRequestStep(1);setRequestOpen(true)}
  async function createAndPay(){if(!draft.categoryId||!draft.title.trim()||!draft.description.trim()||!draft.address.trim()||Number(draft.budget)<10){setError(t.required);return}setLoading(true);setError("");try{const created:JobSummary=await api("/jobs",{method:"POST",body:JSON.stringify({categoryId:draft.categoryId,title:draft.title,description:draft.description,address:draft.address,budgetCents:Math.round(Number(draft.budget)*100),lat:draft.lat,lng:draft.lng})});const methods:PaymentMethodSummary[]=await api("/payments/methods");const method=methods.find(item=>item.providerType==="MOCK")??methods[0];if(!method)throw new Error(t.apiError);const checkout:CheckoutResponse=await api("/payments/checkout",{method:"POST",body:JSON.stringify({jobId:created.id,providerId:method.providerId,method:method.method,idempotencyKey:`mobile:${created.id}:${method.method}`})});if(checkout.mode==="mock")await api(`/payments/${checkout.payment.id}/mock-confirm`,{method:"POST",body:JSON.stringify({outcome:"success"})});setRequestStep(3);await refresh()}catch(caught){setError(caught instanceof Error?caught.message:t.apiError)}finally{setLoading(false)}}
  function openJob(item:JobSummary){setJob(item);setScreen(item.status==="COMPLETED"?"review":"request")}
  function localePicker(){return <label className="locale-picker"><Menu/><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}>{locales.map(item=><option key={item} value={item}>{localeNames[item]}</option>)}</select></label>}

  if(user?.mustChangePassword)return <main className="client-stage"><section className="phone-shell password-screen"><BubbleLogo/><form onSubmit={changeRequiredPassword}><h1>{t.changePassword}</h1><label>{t.temporary}<input name="currentPassword" type="password" required/></label><label>{t.newPassword}<input name="newPassword" type="password" minLength={8} required/></label><button className="lime-button" disabled={loading}>{t.save}</button>{error&&<em>{error}</em>}</form></section></main>;

  return <main className="client-stage">
    <section className={`phone-shell screen-${screen}`}>
      {screen==="splash"&&<div className="splash-screen"><header>{localePicker()}</header><div className="splash-logo"><BubbleLogo/></div><div className="tagline"><h1>{t.tagline1}<br/><span>{t.tagline2}</span></h1><p>{t.taglineSub}</p></div><div className="splash-actions"><button className="lime-button" onClick={()=>setScreen("home")}>{t.getStarted}</button><button className="white-button" onClick={()=>{setAuthMode("login");setAuthOpen(true)}}>{t.login}</button></div><ToolCloud/></div>}

      {screen==="home"&&<div className="home-screen"><header className="mobile-header"><div>{user?<><small>{t.hello},</small><strong>{user.name.split(" ")[0]}</strong></>:<><small>{t.welcome}</small><strong>FIX MY</strong></>}</div><div>{localePicker()}<button className="round-button"><Bell/></button></div></header><section className="question"><div><h1>{t.need}<br/><span>{t.help}</span> {t.today}</h1></div><BubbleIllustration kind="person"/></section><label className="search-bar"><Search/><input placeholder={t.search}/></label><section className="category-grid">{categories.slice(0,5).map((category,index)=><button key={category.id} onClick={()=>startRequest(category.id)}><i className={index%2?"lime":"blue"}>{categoryIcon(category.slug)}</i><span>{category.names[locale]}</span></button>)}<button onClick={()=>startRequest()}><i className="lime"><MoreHorizontal/></i><span>{t.more}</span></button></section><section className="fast-card"><div><h2>{t.fast}</h2><p>{t.fastSub}</p><button onClick={()=>startRequest()}>{t.requestNow}</button></div><BubbleIllustration kind="clock"/></section><section className="recent"><header><h2>{t.recent}</h2><button>{t.viewAll}</button></header>{jobs.length?<button className="request-row" onClick={()=>openJob(jobs[0]!)}><i><Wrench/></i><span><strong>{jobs[0]!.title}</strong><small>{jobs[0]!.category}</small></span><em>{translations[locale].inProgress}</em><ChevronRight/></button>:<div className="empty-row">{t.noRequests}</div>}</section><BottomNav t={t} active="home" onHome={()=>setScreen("home")} onAdd={()=>startRequest()} onRequests={()=>jobs[0]&&openJob(jobs[0])}/>{user&&<button className="logout-mini" onClick={logout}><LogOut/>{t.logout}</button>}</div>}

      {screen==="request"&&<div className="request-screen"><ScreenHeader title={t.myRequest} back={()=>setScreen("home")}/><section className="service-hero"><div><h1>{job?.title??"Leaky Faucet"}</h1><p>{job?.category??t.repairs}</p><em>{t.inProgress}</em></div><BubbleIllustration kind="faucet"/></section><section className="arrival-card"><div><h2>{t.onWay}</h2><p>{t.arrival}</p><strong>{job?.etaMinutes||18} <small>{t.minutes}</small></strong></div><BubbleIllustration kind="van"/></section><MapCard/><section className="pro-card"><div className="avatar">JD</div><span><strong>{job?.pro?.name??"John D."}</strong><small><Star fill="currentColor"/> {job?.pro?.rating?.toFixed(1)??"4.9"}</small><em>{job?.pro?.profession??t.plumber}</em></span><button className="call"><Phone/></button><button className="chat"><MessageCircle/></button></section><button className="review-link" onClick={()=>setScreen("review")}>{t.rateTitle}<ChevronRight/></button></div>}

      {screen==="review"&&<div className="review-screen"><ScreenHeader title={t.rateTitle} back={()=>setScreen("request")}/><BubbleIllustration kind="thumb"/><h2>{t.experience}</h2><div className="stars">{[1,2,3,4,5].map(value=><button key={value} className={value<=rating?"filled":""} onClick={()=>setRating(value)}><Star fill={value<=rating?"currentColor":"none"}/></button>)}</div><strong className="great">{t.great}</strong><textarea placeholder={t.comment}/><button className="lime-button" onClick={()=>{setNotice(t.ratingSaved);setScreen("home")}}>{t.submit}</button><button className="skip" onClick={()=>setScreen("home")}>{t.skip}</button><div className="review-wave"/></div>}
    </section>

    {authOpen&&<div className="modal-back"><form className="auth-card" onSubmit={submitAuth}><button type="button" className="modal-close" onClick={()=>setAuthOpen(false)}><X/></button><BubbleLogo/><h2>{authMode==="login"?t.login:t.register}</h2>{authMode==="register"&&<label>{t.name}<input name="name" required/></label>}<label>{t.email}<input name="email" type="email" defaultValue={authMode==="login"?"client@fixmy.demo":""} required/></label><label>{t.password}<input name="password" type="password" defaultValue={authMode==="login"?"Client123!":""} minLength={6} required/></label><button className="lime-button" disabled={loading}>{loading?"...":t.continue}</button><p>{t.demoHint}</p><button type="button" className="auth-switch" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?t.register:t.login}</button>{error&&<em>{error}</em>}</form></div>}

    {requestOpen&&<div className="modal-back"><section className="request-modal"><button className="modal-close" onClick={()=>setRequestOpen(false)}><X/></button>{requestStep===1&&<><span>1 / 3</span><h2>{t.requestNow}</h2><label>{t.service}<select value={draft.categoryId} onChange={e=>setDraft({...draft,categoryId:e.target.value})}>{categories.map(category=><option key={category.id} value={category.id}>{category.names[locale]}</option>)}</select></label><label>{t.title}<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>{t.description}<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>{t.address}<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>{t.budget}<input type="number" min="10" value={draft.budget} onChange={e=>setDraft({...draft,budget:e.target.value})}/></label><button className="lime-button" onClick={()=>{if(!draft.title||!draft.description){setError(t.required);return}setError("");setRequestStep(2)}}>{t.review}</button></>}{requestStep===2&&<><span>2 / 3</span><h2>{t.review}</h2><div className="request-summary"><small>{t.service}</small><strong>{selectedCategory?.names[locale]}</strong><small>{t.title}</small><strong>{draft.title}</strong><p>{draft.description}</p><small>{t.address}</small><strong>{draft.address}</strong><b>€{Number(draft.budget).toFixed(2)}</b></div><div className="modal-actions"><button className="white-button" onClick={()=>setRequestStep(1)}>{t.back}</button><button className="lime-button" disabled={loading} onClick={createAndPay}>{loading?"...":t.pay}</button></div></>}{requestStep===3&&<div className="success-state"><i><Check/></i><h2>{t.success}</h2><p>{t.successSub}</p><button className="lime-button" onClick={()=>{setRequestOpen(false);setScreen("home")}}>{t.close}</button></div>}{error&&<em className="form-error">{error}</em>}</section></div>}
    {notice&&<div className="notice" onClick={()=>setNotice("")}>{notice}</div>}
  </main>
}

function ScreenHeader({title,back}:{title:string;back:()=>void}){return <header className="screen-header"><button onClick={back}><ArrowLeft/></button><h1>{title}</h1><button><MoreHorizontal/></button></header>}
function MapCard(){return <div className="map-card"><svg viewBox="0 0 320 170" role="img" aria-label="Route map"><path className="street" d="M-10 45L330 135M30 -5L145 180M170 -10L260 180M-10 120L330 25M80 -10L-5 160M330 70L170 180"/><path className="route" d="M62 128 L100 128 L115 91 L150 98 L174 44 L246 52"/><circle cx="62" cy="128" r="15"/><circle cx="62" cy="128" r="8" className="pro-dot"/><path className="pin" d="M246 33c-12 0-21 9-21 21 0 16 21 32 21 32s21-16 21-32c0-12-9-21-21-21z"/><path className="house" d="M237 55l9-8 9 8v11h-18z"/></svg></div>}
function BottomNav({t,active,onHome,onAdd,onRequests}:{t:ClientCopy;active:string;onHome:()=>void;onAdd:()=>void;onRequests:()=>void}){return <nav className="bottom-nav"><button className={active==="home"?"active":""} onClick={onHome}><Home/><span>{t.home}</span></button><button onClick={onRequests}><Clock3/><span>{t.requests}</span></button><button className="add" onClick={onAdd}><Plus/></button><button><MessageCircle/><span>{t.messages}</span></button><button><UserRound/><span>{t.profile}</span></button></nav>}
