"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { loadStripe } from "@stripe/stripe-js";
import type { AuthResponse, CheckoutResponse, JobSummary, Locale, PaymentMethodSummary, ProSummary, ServiceCategory, SessionUser } from "@fixmy/contracts";
import { ArrowRight, Check, ChevronDown, Clock3, CreditCard, MapPin, Search, ShieldCheck, Sparkles, Star, WalletCards, Wrench, X } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "/backend";
const fallback: ServiceCategory[] = [];
const statusLabels: Record<string,string> = { DRAFT:"Borrador",PAYMENT_PENDING:"Pago pendiente",PAYMENT_FAILED:"Pago fallido",OPEN:"Buscando Pro",ASSIGNED:"Pro asignado",PRO_EN_ROUTE:"Pro en camino",IN_PROGRESS:"Trabajo en curso",COMPLETED:"Completado",CANCELLED:"Cancelado" };
const copy = {
  es:{hello:"¡Hola! ¿Qué necesitas arreglar hoy?",sub:"Profesionales verificados, cerca de ti y listos para ayudarte.",search:"Describe lo que necesitas...",nearby:"Pros disponibles cerca",book:"Solicitar ayuda",popular:"Servicios populares"},
  fr:{hello:"Bonjour ! Que faut-il réparer ?",sub:"Des professionnels vérifiés, proches de vous.",search:"Décrivez votre besoin...",nearby:"Pros disponibles à proximité",book:"Demander de l'aide",popular:"Services populaires"},
  nl:{hello:"Hallo! Wat moet er vandaag gebeuren?",sub:"Geverifieerde vakmensen, dichtbij en klaar om te helpen.",search:"Beschrijf wat je nodig hebt...",nearby:"Pros in de buurt",book:"Hulp aanvragen",popular:"Populaire diensten"},
  en:{hello:"Hi! What needs fixing today?",sub:"Verified professionals, nearby and ready to help.",search:"Describe what you need...",nearby:"Pros available nearby",book:"Request help",popular:"Popular services"},
  pt:{hello:"Olá! O que precisa de conserto?",sub:"Profissionais verificados, perto de você.",search:"Descreva o que precisa...",nearby:"Pros disponíveis por perto",book:"Solicitar ajuda",popular:"Serviços populares"},
} as const;

type Draft = { categoryId:string; title:string; description:string; address:string; budget:string; lat:number; lng:number };
const emptyDraft:Draft={categoryId:"",title:"",description:"",address:"Brussels 1000, Belgium",budget:"85",lat:50.8467,lng:4.3525};

function StripeCheckout({checkout,method,onDone,onError}:{checkout:CheckoutResponse;method:PaymentMethodSummary;onDone:()=>void;onError:(message:string)=>void}){
  const mount=useRef<HTMLDivElement>(null); const [ready,setReady]=useState(false); const [paying,setPaying]=useState(false); const elementsRef=useRef<any>(null);
  useEffect(()=>{let active=true;(async()=>{if(!checkout.clientSecret||!method.publicKey||!mount.current)return;const stripe=await loadStripe(method.publicKey);if(!stripe||!active)return;const elements=stripe.elements({clientSecret:checkout.clientSecret,appearance:{theme:"stripe",variables:{colorPrimary:"#1769e8",borderRadius:"12px"}}});const payment=elements.create("payment");payment.mount(mount.current);elementsRef.current={stripe,elements,payment};payment.on("ready",()=>setReady(true));})();return()=>{active=false;elementsRef.current?.payment?.destroy()};},[checkout.clientSecret,method.publicKey]);
  async function confirm(){if(!elementsRef.current)return;setPaying(true);const {stripe,elements}=elementsRef.current;const result=await stripe.confirmPayment({elements,confirmParams:{return_url:window.location.origin+"/?payment_return=1"},redirect:"if_required"});setPaying(false);if(result.error)onError(result.error.message??"No se pudo confirmar el pago");else onDone()}
  return <div className="stripe-box"><div ref={mount}/><button className="primary full" disabled={!ready||paying} onClick={confirm}>{paying?"Procesando...":"Pagar de forma segura"}</button></div>
}

export default function HomePage(){
  const[locale,setLocale]=useState<Locale>("es");const[categories,setCategories]=useState<ServiceCategory[]>(fallback);const[selected,setSelected]=useState("");const[description,setDescription]=useState("");const[token,setToken]=useState("");const[user,setUser]=useState<SessionUser|null>(null);const[jobs,setJobs]=useState<JobSummary[]>([]);const[job,setJob]=useState<JobSummary|null>(null);const[authOpen,setAuthOpen]=useState(false);const[authMode,setAuthMode]=useState<"login"|"register">("register");const[pendingRequest,setPendingRequest]=useState(false);const[categoryOpen,setCategoryOpen]=useState(false);const[categoryPros,setCategoryPros]=useState<ProSummary[]>([]);const[categoryLoading,setCategoryLoading]=useState(false);const[wizard,setWizard]=useState(false);const[step,setStep]=useState(1);const[draft,setDraft]=useState<Draft>(emptyDraft);const[methods,setMethods]=useState<PaymentMethodSummary[]>([]);const[methodKey,setMethodKey]=useState("");const[checkout,setCheckout]=useState<CheckoutResponse|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[fixiOpen,setFixiOpen]=useState(false);const t=copy[locale];
  const category=useMemo(()=>categories.find(c=>c.id===(draft.categoryId||selected)),[categories,draft.categoryId,selected]);const selectedMethod=methods.find(m=>`${m.providerId}:${m.method}`===methodKey);
  useEffect(()=>{setToken(localStorage.getItem("fixmy_client_token")??"");fetch(`${API}/api/categories`).then(r=>r.ok?r.json():Promise.reject()).then((list:ServiceCategory[])=>{setCategories(list);const first=list[0];if(first){setSelected(first.id);setDraft(d=>({...d,categoryId:d.categoryId||first.id}))}}).catch(()=>setError("No se pudo cargar el catálogo"))},[]);
  useEffect(()=>{if(token)refreshClient()},[token]);useEffect(()=>{if(!token)return;const timer=setInterval(refreshClient,5000);return()=>clearInterval(timer)},[token]);
  async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}/api${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...options.headers}});const body=await r.json().catch(()=>({}));if(r.status===401){logout();throw new Error("Tu sesión expiró. Inicia sesión nuevamente.")}if(!r.ok)throw new Error(Array.isArray(body.message)?body.message.join(". "):body.message??"Error de la API");return body}
  async function refreshClient(){try{const me=await api("/auth/me");if(me.role!=="CLIENT")throw new Error("Usa una cuenta Cliente");setUser(me);if(me.mustChangePassword){setJobs([]);return}const list=await api("/jobs/mine");setJobs(list);if(job){const current=list.find((item:JobSummary)=>item.id===job.id);if(current)setJob(current)}}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function changeRequiredPassword(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);const currentPassword=String(f.get("currentPassword")??"");const newPassword=String(f.get("newPassword")??"");const confirmPassword=String(f.get("confirmPassword")??"");try{if(newPassword!==confirmPassword)throw new Error("Las contraseñas nuevas no coinciden");await api("/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword,newPassword})});setUser(current=>current?{...current,mustChangePassword:false}:current);setMessage("Contraseña actualizada. Tu cuenta está lista.");await refreshClient()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  async function submitAuth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{const path=authMode==="login"?"/auth/login":"/auth/register/client";const r=await fetch(`${API}/api${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),email:f.get("email"),password:f.get("password")})});const data=await r.json();if(!r.ok)throw new Error(data.message??"No se pudo autenticar");const auth=data as AuthResponse;if(auth.user.role!=="CLIENT")throw new Error("Esta no es una cuenta Cliente");localStorage.setItem("fixmy_client_token",auth.token);setToken(auth.token);setUser(auth.user);setAuthOpen(false);if(pendingRequest){setPendingRequest(false);setCategoryOpen(false);launchWizard()}else{setMessage("Sesión iniciada. Ya puedes solicitar el servicio.")}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  function logout(){localStorage.removeItem("fixmy_client_token");setToken("");setUser(null);setJobs([]);setJob(null)}
  function launchWizard(){setDraft(d=>({...d,categoryId:d.categoryId||selected,title:d.title||description,description:d.description||description}));setWizard(true);setStep(1);setError("");setMessage("")}
  function openWizard(){if(!user){setPendingRequest(true);setAuthMode("register");setAuthOpen(true);return}setCategoryOpen(false);launchWizard()}
  async function openCategory(item:ServiceCategory){setSelected(item.id);setDraft(d=>({...d,categoryId:item.id}));setCategoryOpen(true);setCategoryLoading(true);setCategoryPros([]);setError("");try{const r=await fetch(`${API}/api/categories/${item.id}/pros?lat=${draft.lat}&lng=${draft.lng}`);const body=await r.json().catch(()=>[]);if(!r.ok)throw new Error(body.message??"No se pudieron cargar los Pros");setCategoryPros(body)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setCategoryLoading(false)}}
  function useLocation(){if(!navigator.geolocation){setError("La geolocalización no está disponible");return}navigator.geolocation.getCurrentPosition(p=>{setDraft(d=>({...d,lat:p.coords.latitude,lng:p.coords.longitude}));setMessage("Ubicación del dispositivo agregada")},()=>setError("No se pudo obtener tu ubicación"))}
  function nextDetails(){if(!draft.categoryId||!draft.title.trim()||!draft.description.trim()||!draft.address.trim()||Number(draft.budget)<10){setError("Completa categoría, título, descripción, dirección y un presupuesto mínimo de €10");return}setError("");setStep(2)}
  async function createAndLoadPayments(){setLoading(true);setError("");try{const created:JobSummary=await api("/jobs",{method:"POST",body:JSON.stringify({categoryId:draft.categoryId,title:draft.title,description:draft.description,address:draft.address,budgetCents:Math.round(Number(draft.budget)*100),lat:draft.lat,lng:draft.lng})});setJob(created);const list:PaymentMethodSummary[]=await api("/payments/methods");if(!list.length)throw new Error("No hay métodos de pago activos. Activa uno desde Administración.");setMethods(list);const first=list[0]!;setMethodKey(`${first.providerId}:${first.method}`);setStep(3);await refreshClient()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  async function startCheckout(){if(!job||!selectedMethod)return;setLoading(true);setError("");try{const result:CheckoutResponse=await api("/payments/checkout",{method:"POST",body:JSON.stringify({jobId:job.id,providerId:selectedMethod.providerId,method:selectedMethod.method,idempotencyKey:`web:${job.id}:${selectedMethod.providerId}:${selectedMethod.method}`})});setCheckout(result);setStep(4)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  async function confirmMock(outcome:"success"|"failure"){if(!checkout)return;setLoading(true);try{await api(`/payments/${checkout.payment.id}/mock-confirm`,{method:"POST",body:JSON.stringify({outcome})});await refreshClient();setStep(outcome==="success"?5:3);setMessage(outcome==="success"?"Pago confirmado. Tu solicitud ya está visible para los Pros.":"Pago rechazado. Puedes elegir otro método y reintentar.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  function closeWizard(){setWizard(false);setCheckout(null);setMethods([]);setStep(1);setDraft({...emptyDraft,categoryId:selected});refreshClient()}
  if(user?.mustChangePassword)return <main className="password-gate"><form onSubmit={changeRequiredPassword}><div className="brand official"><img src="/brand/fixmy-official-logo.jpg" alt="FIX MY"/></div><span>SEGURIDAD DE LA CUENTA</span><h1>Crea una nueva contraseña</h1><p>Administración restableció tu acceso. Por seguridad, debes sustituir la contraseña temporal antes de usar FIX MY.</p><label>Contraseña temporal<input name="currentPassword" type="password" required/></label><label>Nueva contraseña<input name="newPassword" type="password" minLength={8} required/></label><label>Confirmar nueva contraseña<input name="confirmPassword" type="password" minLength={8} required/></label><button className="primary full" disabled={loading}>{loading?"Actualizando...":"Guardar y continuar"}</button><button type="button" className="auth-switch" onClick={logout}>Cerrar sesión</button>{error&&<em>{error}</em>}</form></main>;
  return <main>
    <header className="nav shell"><a className="brand official" href="#top"><img src="/brand/fixmy-official-logo.jpg" alt="FIX MY"/></a><nav><a href="#services">Servicios</a><a href="#how">Cómo funciona</a><a href="#account">Mis solicitudes</a></nav><div className="nav-actions"><label className="lang"><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="es">ES</option><option value="fr">FR</option><option value="nl">NL</option><option value="en">EN</option><option value="pt">PT</option></select><ChevronDown size={14}/></label>{user?<><span className="user-chip">{user.name}</span><button className="ghost" onClick={logout}>Salir</button></>:<button className="ghost" onClick={()=>{setPendingRequest(false);setAuthMode("login");setAuthOpen(true)}}>Entrar</button>}<a className="primary small pro-link" href="http://localhost:3002">Soy Pro</a></div></header>
    <section className="hero shell" id="top"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> Friendly. Smart. Helpful.</div><h1>{t.hello}</h1><p>{t.sub}</p><div className="searchbox"><Search size={22}/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder={t.search}/><button onClick={openWizard}>{t.book}<ArrowRight size={18}/></button></div><div className="trust-row"><span><ShieldCheck size={17}/> Pros verificados</span><span><Clock3 size={17}/> Respuesta rápida</span><span><CreditCard size={17}/> Pago protegido</span></div></div><div className="agent-card"><div className="agent-orbit"><div className="agent-face"><img src="/brand/fixi-mascot.jpg" alt="Fixi"/></div><span className="online-dot"/></div><div><strong>Fixi, tu Help Agent</strong><p>Cuéntame qué pasó. Te guío para publicar una solicitud completa.</p><button onClick={()=>setFixiOpen(true)}>Pedir orientación</button></div></div></section>
    <section className="categories shell" id="services"><div className="section-head"><div><span>EXPLORA</span><h2>{t.popular}</h2></div></div><div className="category-grid">{categories.map((item,index)=><button key={item.id} onClick={()=>openCategory(item)} className={`category ${selected===item.id?"selected":""}`}><span className={`icon color-${index%4}`}><Wrench size={25}/></span><strong>{item.names[locale]}</strong><small>{item.activePros} {t.nearby}</small><ArrowRight className="cat-arrow" size={17}/></button>)}</div></section>
    <section className="steps shell" id="how"><div className="section-head"><div><span>REAL Y SEGURO</span><h2>Del problema al trabajo terminado.</h2></div></div><div className="step-grid">{[["01","Describe y ubica","Completa los datos reales y el presupuesto."],["02","Elige cómo pagar","Selecciona un método activado por Administración."],["03","Sigue al Pro","La solicitud se publica solo después del pago."]].map(([n,title,text])=><article key={n}><b>{n}</b><div className="step-icon"><Check size={22}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    {user&&<section className="my-jobs shell" id="account"><div className="section-head"><div><span>MI CUENTA</span><h2>Mis solicitudes</h2></div><button onClick={refreshClient}>Actualizar</button></div><div>{jobs.length===0?<p>Aún no has creado solicitudes.</p>:jobs.map(item=><button key={item.id} onClick={()=>setJob(item)}><strong>{item.title}</strong><span>{item.category} · €{((item.budgetCents??0)/100).toFixed(2)}</span><em>{statusLabels[item.status]??item.status}</em></button>)}</div></section>}
    {categoryOpen&&category&&<div className="category-overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setCategoryOpen(false)}}><section className="category-detail"><header><div><span className="kicker">SERVICIO DISPONIBLE</span><h2>{category.names[locale]}</h2><p>{category.description}</p></div><button className="category-close" onClick={()=>setCategoryOpen(false)}><X/></button></header><div className="category-summary"><div><strong>{categoryPros.length}</strong><span>Pros aprobados</span></div><div><strong>Pago protegido</strong><span>La solicitud se publica después del pago</span></div></div><div className="pro-list"><div className="pro-list-head"><h3>Profesionales disponibles</h3><button className="location" onClick={useLocation}><MapPin size={16}/> Usar mi ubicación</button></div>{categoryLoading?<div className="category-state"><span className="spinner"/><strong>Buscando Pros aprobados...</strong></div>:categoryPros.length===0?<div className="category-state"><Wrench/><strong>Aún no hay Pros aprobados en esta categoría</strong><p>Puedes crear la solicitud y la Administración podrá incorporar nuevos profesionales.</p></div>:categoryPros.map(pro=><article className="pro-card" key={pro.id}><div className="pro-avatar">{pro.name.slice(0,1).toUpperCase()}</div><div className="pro-main"><div className="pro-title"><strong>{pro.name}</strong><span className={pro.isOnline?"online":"offline"}>{pro.isOnline?"Disponible ahora":"Disponible por solicitud"}</span></div><p>{pro.profession}</p><div className="pro-meta"><span><Star size={15} fill="currentColor"/> {pro.rating.toFixed(1)}</span><span>{pro.completedJobs} trabajos</span><span><MapPin size={15}/> {pro.distanceKm.toFixed(1)} km</span></div></div></article>)}</div><footer><button className="ghost" onClick={()=>setCategoryOpen(false)}>Seguir explorando</button><button className="primary category-request" onClick={openWizard}>Solicitar {category.names[locale]} <ArrowRight size={18}/></button></footer></section></div>}
    {job&&!wizard&&<div className="job-drawer"><button className="close" onClick={()=>setJob(null)}>×</button><div className="status-icon"><Wrench/></div><span className="kicker">SOLICITUD</span><h2>{statusLabels[job.status]??job.status}</h2><p>{job.title}</p><p>{job.address}</p>{job.pro&&<p><b>{job.pro.name}</b> · {job.pro.profession}</p>}{job.payment&&<div className="payment-line"><WalletCards/><span>{job.payment.providerName}<small>{job.payment.status} · €{(job.payment.amountCents/100).toFixed(2)}</small></span></div>}<button className="primary full" onClick={refreshClient}>Actualizar estado</button></div>}
    {authOpen&&<div className="auth-overlay"><form onSubmit={submitAuth}><button type="button" className="auth-close" onClick={()=>{setAuthOpen(false);setPendingRequest(false)}}>×</button><span>FIX MY CLIENT</span><h2>{authMode==="login"?"Iniciar sesión":"Crear cuenta Cliente"}</h2>{pendingRequest&&<p className="auth-intent">Después de entrar continuaremos automáticamente con tu solicitud de {category?.names[locale]??"servicio"}.</p>}{authMode==="register"&&<input name="name" placeholder="Nombre completo" required/>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Contraseña" minLength={6} required/><button className="primary full" disabled={loading}>{loading?"Procesando...":"Continuar"}</button>{error&&<em>{error}</em>}<button type="button" className="auth-switch" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Crear cuenta nueva":"Ya tengo cuenta"}</button></form></div>}
    {wizard&&<div className="wizard-overlay"><section className="wizard"><header><div><span>PASO {step} DE 5</span><h2>{step===1?"Cuéntanos el problema":step===2?"Revisa la solicitud":step===3?"Elige cómo pagar":step===4?"Confirma el pago":"Solicitud publicada"}</h2></div><button onClick={closeWizard}><X/></button></header><div className="wizard-progress"><i className={step>=1?"on":""}/><i className={step>=2?"on":""}/><i className={step>=3?"on":""}/><i className={step>=4?"on":""}/><i className={step>=5?"on":""}/></div>
      {step===1&&<div className="form-grid"><label>Servicio<select value={draft.categoryId} onChange={e=>setDraft({...draft,categoryId:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.names.es}</option>)}</select></label><label>Título<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Ej. Grifo con fuga"/></label><label className="wide">Descripción<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Describe el problema y cuándo empezó"/></label><label className="wide">Dirección<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/><button type="button" className="location" onClick={useLocation}><MapPin size={16}/> Usar mi ubicación</button></label><label>Presupuesto (€)<input type="number" min="10" max="10000" step="1" value={draft.budget} onChange={e=>setDraft({...draft,budget:e.target.value})}/></label><button className="primary next" onClick={nextDetails}>Revisar <ArrowRight/></button></div>}
      {step===2&&<div className="review"><div><small>Servicio</small><strong>{category?.names.es}</strong></div><div><small>Problema</small><strong>{draft.title}</strong><p>{draft.description}</p></div><div><small>Dirección</small><strong>{draft.address}</strong></div><div><small>Total autorizado</small><strong className="price">€{Number(draft.budget).toFixed(2)}</strong></div><div className="wizard-actions"><button className="ghost" onClick={()=>setStep(1)}>Editar</button><button className="primary" disabled={loading} onClick={createAndLoadPayments}>{loading?"Guardando...":"Continuar al pago"}</button></div></div>}
      {step===3&&<div className="payment-methods"><p>Solo se muestran los métodos activados por Administración.</p>{methods.map(m=><label key={`${m.providerId}:${m.method}`} className={methodKey===`${m.providerId}:${m.method}`?"chosen":""}><input type="radio" name="method" checked={methodKey===`${m.providerId}:${m.method}`} onChange={()=>setMethodKey(`${m.providerId}:${m.method}`)}/><CreditCard/><span><strong>{m.label}</strong><small>{m.providerName} · {m.mode}</small></span></label>)}<div className="wizard-actions"><button className="ghost" onClick={()=>setStep(2)}>Atrás</button><button className="primary" disabled={!selectedMethod||loading} onClick={startCheckout}>{loading?"Preparando...":"Pagar ahora"}</button></div></div>}
      {step===4&&checkout&&selectedMethod&&<div className="checkout-panel"><div className="checkout-total"><span>Total</span><strong>€{(checkout.payment.amountCents/100).toFixed(2)}</strong></div>{checkout.mode==="mock"?<><div className="test-payment"><ShieldCheck/><div><strong>Entorno de prueba</strong><p>Simula el resultado sin usar dinero real. Así puedes probar todo el marketplace ahora.</p></div></div><button className="primary full" disabled={loading} onClick={()=>confirmMock("success")}>Aprobar pago de prueba</button><button className="danger-link" disabled={loading} onClick={()=>confirmMock("failure")}>Simular pago rechazado</button></>:checkout.mode==="stripe"?<StripeCheckout checkout={checkout} method={selectedMethod} onDone={()=>{setMessage("Stripe está procesando el pago. Esperando webhook...");refreshClient()}} onError={setError}/>:<p>Este conector requiere completar su flujo externo.</p>}</div>}
      {step===5&&<div className="success-panel"><div className="success-icon"><Check/></div><h3>Solicitud publicada</h3><p>El pago fue confirmado y los Pros compatibles ya pueden verla.</p><button className="primary" onClick={closeWizard}>Ver mis solicitudes</button></div>}{error&&<div className="wizard-error">{error}</div>}</section></div>}
    {fixiOpen&&<div className="fixi-panel"><button onClick={()=>setFixiOpen(false)}><X/></button><img src="/brand/fixi-mascot.jpg" alt="Fixi"/><h3>¿Cómo puedo ayudarte?</h3><p>Para crear una solicitud real, prepara una descripción clara, la dirección y el presupuesto. El trabajo solo será visible para los Pros después de confirmar el pago.</p><button className="primary full" onClick={()=>{setFixiOpen(false);openWizard()}}>Crear solicitud guiada</button></div>}
    {error&&!authOpen&&!wizard&&<div className="error-toast" onClick={()=>setError("")}>{error}</div>}{message&&<div className="success-toast" onClick={()=>setMessage("")}>{message}</div>}<button className="agent-fab fixi-fab" onClick={()=>setFixiOpen(true)}><img src="/brand/fixi-mascot.jpg" alt="Fixi"/><span>Habla con Fixi</span></button>
  </main>
}
