export type UiLocale = "es" | "fr" | "nl" | "en" | "pt";
const dictionaries:Record<Exclude<UiLocale,"es">,Record<string,string>>={
 en:{"Resumen":"Overview","Oportunidades":"Opportunities","Mis trabajos":"My jobs","Mis servicios":"My services","Perfil profesional":"Professional profile","Administra tu actividad":"Manage your activity","Crea tu negocio en FIX MY":"Create your FIX MY business","Nombre completo":"Full name","Profesión o especialidad":"Profession or specialty","Servicio principal":"Main service","Email":"Email","Contraseña (mínimo 6)":"Password (minimum 6)","Entrar al panel":"Enter dashboard","Crear cuenta Pro":"Create Pro account","Cerrar sesión":"Log out","Disponible":"Available","No disponible":"Unavailable","Ver oportunidades":"View opportunities","Trabajos activos":"Active jobs","Ingresos del mes":"Monthly earnings","Valoración":"Rating","Guardar servicios":"Save services","Guardar perfil":"Save profile","Aceptar trabajo":"Accept job","Voy en camino":"I'm on my way","Iniciar trabajo":"Start job","Completar trabajo":"Complete job"},
 fr:{"Resumen":"Aperçu","Oportunidades":"Opportunités","Mis trabajos":"Mes missions","Mis servicios":"Mes services","Perfil profesional":"Profil professionnel","Administra tu actividad":"Gérez votre activité","Crea tu negocio en FIX MY":"Créez votre entreprise FIX MY","Nombre completo":"Nom complet","Profesión o especialidad":"Profession ou spécialité","Servicio principal":"Service principal","Contraseña (mínimo 6)":"Mot de passe (minimum 6)","Entrar al panel":"Accéder au tableau","Crear cuenta Pro":"Créer un compte Pro","Cerrar sesión":"Déconnexion","Disponible":"Disponible","No disponible":"Indisponible","Ver oportunidades":"Voir les opportunités","Trabajos activos":"Missions actives","Ingresos del mes":"Revenus du mois","Valoración":"Note","Guardar servicios":"Enregistrer les services","Guardar perfil":"Enregistrer le profil","Aceptar trabajo":"Accepter la mission","Voy en camino":"Je suis en route","Iniciar trabajo":"Commencer","Completar trabajo":"Terminer"},
 nl:{"Resumen":"Overzicht","Oportunidades":"Kansen","Mis trabajos":"Mijn opdrachten","Mis servicios":"Mijn diensten","Perfil profesional":"Professioneel profiel","Administra tu actividad":"Beheer je activiteit","Crea tu negocio en FIX MY":"Start je FIX MY-bedrijf","Nombre completo":"Volledige naam","Profesión o especialidad":"Beroep of specialiteit","Servicio principal":"Hoofddienst","Contraseña (mínimo 6)":"Wachtwoord (minimaal 6)","Entrar al panel":"Naar dashboard","Crear cuenta Pro":"Pro-account maken","Cerrar sesión":"Uitloggen","Disponible":"Beschikbaar","No disponible":"Niet beschikbaar","Ver oportunidades":"Bekijk kansen","Trabajos activos":"Actieve opdrachten","Ingresos del mes":"Inkomsten deze maand","Valoración":"Beoordeling","Guardar servicios":"Diensten opslaan","Guardar perfil":"Profiel opslaan","Aceptar trabajo":"Opdracht aanvaarden","Voy en camino":"Ik ben onderweg","Iniciar trabajo":"Opdracht starten","Completar trabajo":"Opdracht voltooien"},
 pt:{"Resumen":"Visão geral","Oportunidades":"Oportunidades","Mis trabajos":"Meus trabalhos","Mis servicios":"Meus serviços","Perfil profesional":"Perfil profissional","Administra tu actividad":"Gerencie sua atividade","Crea tu negocio en FIX MY":"Crie seu negócio FIX MY","Nombre completo":"Nome completo","Profesión o especialidad":"Profissão ou especialidade","Servicio principal":"Serviço principal","Contraseña (mínimo 6)":"Senha (mínimo 6)","Entrar al panel":"Entrar no painel","Crear cuenta Pro":"Criar conta Pro","Cerrar sesión":"Sair","Disponible":"Disponível","No disponible":"Indisponível","Ver oportunidades":"Ver oportunidades","Trabajos activos":"Trabalhos ativos","Ingresos del mes":"Receita do mês","Valoración":"Avaliação","Guardar servicios":"Salvar serviços","Guardar perfil":"Salvar perfil","Aceptar trabajo":"Aceitar trabalho","Voy en camino":"Estou a caminho","Iniciar trabajo":"Iniciar trabalho","Completar trabajo":"Concluir trabalho"}
};
const originals=new WeakMap<Node,string>();
export function localizeDocument(locale:UiLocale){if(typeof document==="undefined")return;document.documentElement.lang=locale;const dict=locale==="es"?{}:dictionaries[locale];const apply=()=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const value=node.textContent??"";if(!value.trim())continue;if(!originals.has(node))originals.set(node,value);const original=originals.get(node)!;const key=original.trim();node.textContent=dict[key]?original.replace(key,dict[key]!):original}};apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()}
