export type UiLocale = "es" | "fr" | "nl" | "en" | "pt";
const dictionaries: Record<Exclude<UiLocale,"es">,Record<string,string>> = {
  en:{"Resumen":"Overview","Usuarios":"Users","Clientes":"Clients","Pro Fixers":"Pro Fixers","Servicios":"Services","Trabajos":"Jobs","Pagos":"Payments","Integraciones":"Integrations","Actividad":"Activity","Logs técnicos":"Technical logs","Acceso administrativo":"Admin access","Correo electrónico":"Email","Contraseña":"Password","Entrar al Control Center":"Enter Control Center","El marketplace, bajo control.":"The marketplace, under control.","Actualizar":"Refresh","Actualizando":"Refreshing","Cerrar sesión":"Log out","Buscar por nombre, correo o teléfono":"Search by name, email or phone","Buscar clientes":"Search clients","Buscar Pro, profesión o empresa":"Search Pro, profession or company","Buscar en el catálogo":"Search the catalog","Buscar trabajo, cliente o dirección":"Search job, client or address","Buscar acción, persona o evento":"Search action, person or event","Buscar mensaje, ruta o request ID":"Search message, path or request ID","Todos los estados":"All statuses","Nuevo servicio":"New service","Servicios activos":"Active services","Trabajos activos":"Active jobs","Volumen cobrado":"Processed volume","Reembolsos":"Refunds","Actividad reciente":"Recent activity","Lo que requiere atención":"What needs attention","Ver todo":"View all","Sin resultados":"No results","Errores":"Errors","Advertencias":"Warnings"},
  fr:{"Resumen":"Aperçu","Usuarios":"Utilisateurs","Clientes":"Clients","Servicios":"Services","Trabajos":"Missions","Pagos":"Paiements","Integraciones":"Intégrations","Actividad":"Activité","Logs técnicos":"Journaux techniques","Acceso administrativo":"Accès administrateur","Correo electrónico":"E-mail","Contraseña":"Mot de passe","Entrar al Control Center":"Accéder au centre","El marketplace, bajo control.":"La marketplace sous contrôle.","Actualizar":"Actualiser","Actualizando":"Actualisation","Cerrar sesión":"Déconnexion","Todos los estados":"Tous les statuts","Nuevo servicio":"Nouveau service","Servicios activos":"Services actifs","Trabajos activos":"Missions actives","Volumen cobrado":"Volume encaissé","Reembolsos":"Remboursements","Actividad reciente":"Activité récente","Lo que requiere atención":"À surveiller","Ver todo":"Voir tout","Sin resultados":"Aucun résultat","Errores":"Erreurs","Advertencias":"Avertissements"},
  nl:{"Resumen":"Overzicht","Usuarios":"Gebruikers","Clientes":"Klanten","Servicios":"Diensten","Trabajos":"Opdrachten","Pagos":"Betalingen","Integraciones":"Integraties","Actividad":"Activiteit","Logs técnicos":"Technische logs","Acceso administrativo":"Beheerderstoegang","Correo electrónico":"E-mail","Contraseña":"Wachtwoord","Entrar al Control Center":"Naar Control Center","El marketplace, bajo control.":"De marketplace onder controle.","Actualizar":"Vernieuwen","Actualizando":"Vernieuwen","Cerrar sesión":"Uitloggen","Todos los estados":"Alle statussen","Nuevo servicio":"Nieuwe dienst","Servicios activos":"Actieve diensten","Trabajos activos":"Actieve opdrachten","Volumen cobrado":"Verwerkt volume","Reembolsos":"Terugbetalingen","Actividad reciente":"Recente activiteit","Lo que requiere atención":"Aandachtspunten","Ver todo":"Alles bekijken","Sin resultados":"Geen resultaten","Errores":"Fouten","Advertencias":"Waarschuwingen"},
  pt:{"Resumen":"Visão geral","Usuarios":"Usuários","Clientes":"Clientes","Servicios":"Serviços","Trabajos":"Trabalhos","Pagos":"Pagamentos","Integraciones":"Integrações","Actividad":"Atividade","Logs técnicos":"Logs técnicos","Acceso administrativo":"Acesso administrativo","Correo electrónico":"E-mail","Contraseña":"Senha","Entrar al Control Center":"Entrar no Control Center","El marketplace, bajo control.":"O marketplace sob controle.","Actualizar":"Atualizar","Actualizando":"Atualizando","Cerrar sesión":"Sair","Todos los estados":"Todos os estados","Nuevo servicio":"Novo serviço","Servicios activos":"Serviços ativos","Trabajos activos":"Trabalhos ativos","Volumen cobrado":"Volume recebido","Reembolsos":"Reembolsos","Actividad reciente":"Atividade recente","Lo que requiere atención":"O que exige atenção","Ver todo":"Ver tudo","Sin resultados":"Sem resultados","Errores":"Erros","Advertencias":"Avisos"}
};
const originals=new WeakMap<Node,string>();
const attributeOriginals=new WeakMap<Element,Record<string,string>>();
export function localizeDocument(locale:UiLocale){if(typeof document==="undefined")return;document.documentElement.lang=locale;const dict:Record<string,string>=locale==="es"?{}:dictionaries[locale];const apply=()=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const current=node.textContent??"";if(!current.trim())continue;if(!originals.has(node))originals.set(node,current);const original=originals.get(node)!;const trimmed=original.trim();const translated=dict[trimmed];node.textContent=translated?original.replace(trimmed,translated):original}document.querySelectorAll("input,textarea").forEach(el=>{const attrs=attributeOriginals.get(el)??{placeholder:el.getAttribute("placeholder")??""};attributeOriginals.set(el,attrs);const placeholder=attrs.placeholder??"";const translated=dict[placeholder];if(placeholder)el.setAttribute("placeholder",translated??placeholder)})};apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()}
